env:
    browser: true
    es6: true
    jquery: true
extends: "eslint:recommended"
rules:
    # these just throw too many deceptive errors due to the project's structure
    no-undef: off
    no-unused-vars: off
