rules:
    class-name-format: 0
    colorKeyword: 0
    force-attribute-nesting: 0
    force-element-nesting: 0
    force-pseudo-nesting: 0
    indentation:
        - 1
        -
          size: 4
    mixins-before-declarations: 0
    no-ids: 0
    no-important: 0
    # without these two disabled we just cannot reference external assets
    no-url-domains: 0
    no-url-protocols: 0
    selector-format: 0
    space-between-parens: 0
    variable-name-format: 0
