rules:
    class-name-format: 0
    colorKeyword: 0
    force-pseudo-nesting: 0
    indentation:
        - 1
        -
          size: 4
    mixins-before-declarations: 0
    no-ids: 0
    selector-format: 0
    space-between-parens: 0
    variable-name-format: 0
