name: Lint

on:
  push:
    branches: ['**']
    paths:
      - '**/*.js'
      - '**/*.scss'
      - .github/workflows/lint.yml
  workflow_call:

jobs:
  lint:
    name: Run lint
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      # must come before setup-node
      - name: Setup PNPM
        uses: pnpm/action-setup@v6.0.8
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v6.4.0
        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: JS Lint
        run: npm run eslint

      - name: Style Lint
        # Run stylelint even if eslint fails, we always want a full report
        if: ${{ always() }}
        run: npm run stylelint
