name: Lint

on:
  push:
    branches: ['**']

jobs:
  lint:
    name: Run lint
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # must come before setup-node
      - name: Setup PNPM
        uses: pnpm/action-setup@v4.2.0
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: JS Lint
        run: npx gulp lint

      - name: Style Lint
        run: npx stylelint **/*.scss
